### ISSUE TITLE
How to build TownGeneratorOS

### ISSUE THREAD

**Issue by kmj940101** [watabou/TownGeneratorOS#4]
I love TownGeneratorOS and I'd like to work on it. 
I am new to haxe. I have a problem with building the project.

```
$ haxe -main com.watabou.towngenerator.Main -cp Source -lib openfl:7.1.1 -lib msignal:1.2.4 -lib lime:6.1.0 -xml project.xml 

Source/com/watabou/towngenerator/Main.hx:11: lines 11-33 : Invalid -main : com.watabou.towngenerator.Main does not have static function main
```

Am I missing something? I think it would be helpful if there is more information in README.mb file.
Thank you for your help in advance!

**Comment by kmj940101** [comment]
I am closing this issue for now because of inactivity.

**Comment by zx013** [comment]
I know how to build it, it builds using openfl. So I run the code below. I also modified the versions of lime and openfl.
```
haxelib install lime 7.8.0
haxelib install openfl 9.0.2
haxelib install msignal 1.2.5
haxelib run openfl setup
```
Then I modify project.xml to make the versions of lime and openfl correct.
```
	<haxelib name="lime" version="7.8.0" />
	<haxelib name="openfl" version="9.0.2" />
```
After this, it can build well.
```
openfl build .\project.xml neko
```

**Comment by zx013** [comment]
To fix error in building, modify file like below.
[https://github.com/watabou/TownGeneratorOS/pull/16]()

**Comment by RobertoMaurizzi** [comment]
@zx013 you should fork this repo and make all those fixes in your fork :-)
